//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panfilova_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int ID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
